name: CI

on:
  push:
    branches: [main, develop] # Trigger the workflow on push events to main and develop branches
  pull_request:
    branches: [main, develop] # Trigger the workflow on pull request events targeting main and develop branches

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Check out the repository code to the runner

    - name: Set up Python
      uses: actions/setup-python@v2 # Set up the specified version of Python
      with:
        python-version: '3.x' # Specify the Python version to be used (any 3.x version)

    - name: Install dependencies
      run: python -m pip install --upgrade pip  # Upgrade pip to the latest version

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt  # Install dependencies listed in requirements.txt

    - name: Run tests
      run: pytest  # Run the tests using pytest
